[2023-12-11T21:16:28.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_NASA.get_asteroid_data_task scheduled__2023-10-31T00:00:00+00:00 [queued]>
[2023-12-11T21:16:28.737+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_NASA.get_asteroid_data_task scheduled__2023-10-31T00:00:00+00:00 [queued]>
[2023-12-11T21:16:28.741+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-11T21:16:28.947+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_asteroid_data_task> on 2023-10-31 00:00:00+00:00
[2023-12-11T21:16:29.006+0000] {standard_task_runner.py:57} INFO - Started process 155 to run task
[2023-12-11T21:16:29.040+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_NASA', 'get_asteroid_data_task', 'scheduled__2023-10-31T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dag_nasa.py', '--cfg-path', '/tmp/tmpoxn654_p']
[2023-12-11T21:16:29.063+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask get_asteroid_data_task
[2023-12-11T21:16:39.119+0000] {cli_action_loggers.py:135} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-12-11T21:16:40.160+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_NASA.get_asteroid_data_task scheduled__2023-10-31T00:00:00+00:00 [running]> on host d9b326dafe4c
[2023-12-11T21:16:40.707+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jose Daniel Pérez' AIRFLOW_CTX_DAG_ID='ETL_NASA' AIRFLOW_CTX_TASK_ID='get_asteroid_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-31T00:00:00+00:00'
[2023-12-11T21:16:42.177+0000] {logging_mixin.py:154} INFO - Conexion exitosa
[2023-12-11T21:16:42.210+0000] {python.py:194} INFO - Done. Returned value was:            Nombre  ... Distancia a la Tierra (kilómetros)
0    (2006 UL185)  ...                 33691526.585975446
1    (2013 TC136)  ...                 69415696.996901268
2      (2017 RP2)  ...                 42690875.045076463
3      (2019 TA7)  ...                   48048608.3317157
4      (2020 TH6)  ...                 16431658.167807157
..            ...  ...                                ...
225    (2023 UU1)  ...                   526036.271085811
226    (2023 UR3)  ...                    2577400.7585282
227   (2023 UM10)  ...                   750370.574095725
228    (2023 VF1)  ...                 22799576.563098442
229    (2023 WH3)  ...                  5910104.303006451

[230 rows x 4 columns]
[2023-12-11T21:16:42.544+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_NASA, task_id=get_asteroid_data_task, execution_date=20231031T000000, start_date=20231211T211628, end_date=20231211T211642
[2023-12-11T21:16:42.605+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-11T21:16:42.663+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
